version: 2
multi-ecosystem-groups:
  bundled-dependencies:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
      - "security"
    target-branch: "main"
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 1
    patterns:
      - "*"
    multi-ecosystem-group: "bundled-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    patterns:
      - "*"
    multi-ecosystem-group: "bundled-dependencies"
