version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "security"
    groups:
      nuget-non-breaking:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      nuget-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "security"
    groups:
      github-actions-non-breaking:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
